In [ ]:
import numpy as np

In [ ]:
python_list = [3,2,5,8,4,9,7,6,1]
array = np.array(python_list)
array

array([3, 2, 5, 8, 4, 9, 7, 6, 1])

In [ ]:
type(array)

numpy.ndarray

In [ ]:
python_list_of_lists = [[3,2,5],
                       [9,7,1],
                       [4,3,6]]
np.array(python_list_of_lists)

array([[3, 2, 5],
       [9, 7, 1],
       [4, 3, 6]])

In [ ]:
python_list = ["beep",False,56,.945,[3,2,5]]

In [ ]:
numpy_boolean_array = [[True, False], [True, True], [False, True]]

numpy_float_array = [1.9, 5.4, 8.8, 3.6, 3.2]

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.random((2,4))

array([[0.68398342, 0.85545082, 0.42900295, 0.1099469 ],
       [0.76532404, 0.44276362, 0.74646645, 0.63933367]])

In [ ]:
np.arange(-3,4)

array([-3, -2, -1,  0,  1,  2,  3])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(-3, 4, 3)

array([-3,  0,  3])

In [ ]:
array = np.zeros((3, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
array.shape

(3, 5)

In [ ]:
array = np.array([[1, 2], [5, 7], [6, 6]])
array

array([[1, 2],
       [5, 7],
       [6, 6]])

In [ ]:
array.flatten()

array([1, 2, 5, 7, 6, 6])

In [ ]:
array.reshape((2, 3))

array([[1, 2, 5],
       [7, 6, 6]])

In [ ]:
array.reshape((3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
np.array([1.32, 5.78, 175.55]).dtype

dtype('float64')

In [ ]:
int_array = np.array([[1, 2, 3], [4, 5, 6]])
int_array.dtype

dtype('int32')

In [ ]:
np.array(["Introduction","to","NumPy"]).dtype

dtype('<U12')

In [ ]:
np.array([True,"Boop", 42, 42.42])

array(['True', 'Boop', '42', '42.42'], dtype='<U32')

In [ ]:
np.array([True, False, 42]).dtype

dtype('int32')

In [ ]:
np.array([0, 42, 42.42]).dtype

dtype('float64')

## the second session

In [ ]:
array = np.array([2, 4, 6, 8, 10])
array[3]

8

In [ ]:
sudoku_game=[[0,0,4,3,0,0,2,0,9],
             [0,0,5,0,0,9,0,0,1],
             [0,7,0,0,6,0,0,4,3],
             [0,0,6,0,0,2,0,8,7],
             [1,9,0,0,0,7,4,0,0],
             [0,5,0,0,8,3,0,0,0],
             [6,0,0,0,0,0,1,0,5],
             [0,0,3,5,0,8,6,9,0],
             [0,4,2,9,1,0,3,0,0]]
sudoku_game=np.array(sudoku_game)
sudoku_game

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

In [ ]:
sudoku_game[2, 4]

6

In [ ]:
sudoku_game[0]

array([0, 0, 4, 3, 0, 0, 2, 0, 9])

In [ ]:
sudoku_game[:, 3]

array([3, 0, 0, 0, 0, 0, 0, 5, 9])

In [ ]:
array = np.array([2, 4, 6, 8, 10])
array[2:4]

array([6, 8])

In [ ]:
sudoku_game[3:6, 3:6]

array([[0, 0, 2],
       [0, 0, 7],
       [0, 8, 3]])

In [ ]:
sudoku_game[3:6:2, 3:6:2]

array([[0, 2],
       [0, 3]])

In [ ]:
np.sort(sudoku_game)

array([[0, 0, 0, 0, 0, 2, 3, 4, 9],
       [0, 0, 0, 0, 0, 0, 1, 5, 9],
       [0, 0, 0, 0, 0, 3, 4, 6, 7],
       [0, 0, 0, 0, 0, 2, 6, 7, 8],
       [0, 0, 0, 0, 0, 1, 4, 7, 9],
       [0, 0, 0, 0, 0, 0, 3, 5, 8],
       [0, 0, 0, 0, 0, 0, 1, 5, 6],
       [0, 0, 0, 0, 3, 5, 6, 8, 9],
       [0, 0, 0, 0, 1, 2, 3, 4, 9]])

In [ ]:
np.sort(sudoku_game, axis=1)                 #np.sort(sudoku_game)

array([[0, 0, 0, 0, 0, 2, 3, 4, 9],
       [0, 0, 0, 0, 0, 0, 1, 5, 9],
       [0, 0, 0, 0, 0, 3, 4, 6, 7],
       [0, 0, 0, 0, 0, 2, 6, 7, 8],
       [0, 0, 0, 0, 0, 1, 4, 7, 9],
       [0, 0, 0, 0, 0, 0, 3, 5, 8],
       [0, 0, 0, 0, 0, 0, 1, 5, 6],
       [0, 0, 0, 0, 3, 5, 6, 8, 9],
       [0, 0, 0, 0, 1, 2, 3, 4, 9]])

In [ ]:
np.sort(sudoku_game, axis=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 2, 1, 0, 1],
       [0, 4, 3, 0, 0, 3, 2, 0, 3],
       [0, 5, 4, 3, 1, 7, 3, 4, 5],
       [1, 7, 5, 5, 6, 8, 4, 8, 7],
       [6, 9, 6, 9, 8, 9, 6, 9, 9]])

In [ ]:
one_to_five = np.arange(1, 6)
one_to_five

array([1, 2, 3, 4, 5])

In [ ]:
mask = one_to_five % 2 == 0
mask

array([False,  True, False,  True, False])

In [ ]:
one_to_five = np.arange(1, 6)
mask = one_to_five % 2 == 0
one_to_five[mask]

array([2, 4])

In [ ]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [ ]:
classroom_ids_and_sizes[:, 1] % 2 == 0

array([ True, False, False,  True])

In [ ]:
classroom_ids_and_sizes[:, 0][classroom_ids_and_sizes[:, 1] % 2 == 0]

array([1, 4])

In [ ]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [ ]:
import numpy as np

sudoku_game = np.array([[0,0,4,3,0,0,2,0,9],
                        [0,0,5,0,0,9,0,0,1],
                        [0,7,0,0,6,0,0,4,3],
                        [0,0,6,0,0,2,0,8,7],
                        [1,9,0,0,0,7,4,0,0],
                        [0,5,0,0,8,3,0,0,0],
                        [6,0,0,0,0,0,1,0,5],
                        [0,0,3,5,0,8,6,9,0],
                        [0,4,2,9,1,0,3,0,0]])

row_ind, column_ind = np.where(sudoku_game == 0)

# Output the elements at the specified indices
for row, col in zip(row_ind, column_ind):
    element = sudoku_game[row, col]
    print(f"Element at row {row}, column {col}: {element}")


Element at row 0, column 0: 0
Element at row 0, column 1: 0
Element at row 0, column 4: 0
Element at row 0, column 5: 0
Element at row 0, column 7: 0
Element at row 1, column 0: 0
Element at row 1, column 1: 0
Element at row 1, column 3: 0
Element at row 1, column 4: 0
Element at row 1, column 6: 0
Element at row 1, column 7: 0
Element at row 2, column 0: 0
Element at row 2, column 2: 0
Element at row 2, column 3: 0
Element at row 2, column 5: 0
Element at row 2, column 6: 0
Element at row 3, column 0: 0
Element at row 3, column 1: 0
Element at row 3, column 3: 0
Element at row 3, column 4: 0
Element at row 3, column 6: 0
Element at row 4, column 2: 0
Element at row 4, column 3: 0
Element at row 4, column 4: 0
Element at row 4, column 7: 0
Element at row 4, column 8: 0
Element at row 5, column 0: 0
Element at row 5, column 2: 0
Element at row 5, column 3: 0
Element at row 5, column 6: 0
Element at row 5, column 7: 0
Element at row 5, column 8: 0
Element at row 6, column 1: 0
Element at

In [ ]:
np.where(classroom_ids_and_sizes[:, 1] % 2 == 0)

(array([0, 3], dtype=int64),)

In [ ]:
sudoku_game=[[0,0,4,3,0,0,2,0,9],
             [0,0,5,0,0,9,0,0,1],
             [0,7,0,0,6,0,0,4,3],
             [0,0,6,0,0,2,0,8,7],
             [1,9,0,0,0,7,4,0,0],
             [0,5,0,0,8,3,0,0,0],
             [6,0,0,0,0,0,1,0,5],
             [0,0,3,5,0,8,6,9,0],
             [0,4,2,9,1,0,3,0,0]]
sudoku_game=np.array(sudoku_game)

In [ ]:
row_ind, column_ind = np.where(sudoku_game == 0)
row_ind, column_ind

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8,
        8, 8], dtype=int64),
 array([0, 1, 4, 5, 7, 0, 1, 3, 4, 6, 7, 0, 2, 3, 5, 6, 0, 1, 3, 4, 6, 2,
        3, 4, 7, 8, 0, 2, 3, 6, 7, 8, 1, 2, 3, 4, 5, 7, 0, 1, 4, 8, 0, 5,
        7, 8], dtype=int64))

In [ ]:
np.where(sudoku_game == 0,"", sudoku_game)

array([['', '', '4', '3', '', '', '2', '', '9'],
       ['', '', '5', '', '', '9', '', '', '1'],
       ['', '7', '', '', '6', '', '', '4', '3'],
       ['', '', '6', '', '', '2', '', '8', '7'],
       ['1', '9', '', '', '', '7', '4', '', ''],
       ['', '5', '', '', '8', '3', '', '', ''],
       ['6', '', '', '', '', '', '1', '', '5'],
       ['', '', '3', '5', '', '8', '6', '9', ''],
       ['', '4', '2', '9', '1', '', '3', '', '']], dtype='<U11')

In [ ]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
new_classrooms = np.array([[5, 30], [6, 17]])
classroom_ids_and_sizes

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [ ]:
new_classrooms

array([[ 5, 30],
       [ 6, 17]])

In [ ]:
np.concatenate((classroom_ids_and_sizes, new_classrooms))

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26],
       [ 5, 30],
       [ 6, 17]])

In [ ]:
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
grade_levels_and_teachers = np.array([[1,"Moahmed"],
                     [1,"Ahmed"],
                     [3,"Beshoy"],
                     [3,"Nadia"]])
np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)

array([['1', '22', '1', 'Moahmed'],
       ['2', '21', '1', 'Ahmed'],
       ['3', '27', '3', 'Beshoy'],
       ['4', '26', '3', 'Nadia']], dtype='<U11')

In [ ]:
classroom_data=[['1','22','1','Mohamed'],
                ['2','21','1','Ahmed'],
                ['3','27','3','Beshoy'],
                ['4','26','3','Nadia']]
classroom_data=np.array(classroom_data)
classroom_data

array([['1', '22', '1', 'Mohamed'],
       ['2', '21', '1', 'Ahmed'],
       ['3', '27', '3', 'Beshoy'],
       ['4', '26', '3', 'Nadia']], dtype='<U7')

In [ ]:
np.delete(classroom_data, 1, axis=0)

array([['1', '22', '1', 'Mohamed'],
       ['3', '27', '3', 'Beshoy'],
       ['4', '26', '3', 'Nadia']], dtype='<U7')

In [ ]:
np.delete(classroom_data, 1, axis=1)

array([['1', '1', 'Mohamed'],
       ['2', '1', 'Ahmed'],
       ['3', '3', 'Beshoy'],
       ['4', '3', 'Nadia']], dtype='<U7')

In [ ]:
np.delete(classroom_data, 15)

array(['1', '22', '1', 'Mohamed', '2', '21', '1', 'Ahmed', '3', '27', '3',
       'Beshoy', '4', '26', '3'], dtype='<U7')

In [ ]:
security_breaches=np.array([[0, 5, 1],
[0, 2, 0],
[1, 1, 2],
[2, 2, 1],
[0, 0, 0]])
security_breaches

array([[0, 5, 1],
       [0, 2, 0],
       [1, 1, 2],
       [2, 2, 1],
       [0, 0, 0]])

In [ ]:
security_breaches.sum()

17

In [ ]:
security_breaches.sum(axis=0)

array([ 3, 10,  4])

In [ ]:
security_breaches.sum(axis=1)

array([6, 2, 4, 5, 0])

In [ ]:
security_breaches.min()

0

In [ ]:
security_breaches.max()

5

In [ ]:
security_breaches.min(axis=1)

array([0, 0, 1, 1, 0])

In [ ]:
security_breaches.mean()

1.1333333333333333

In [ ]:
security_breaches.mean(axis=1)

array([2.        , 0.66666667, 1.33333333, 1.66666667, 0.        ])

In [ ]:
security_breaches.sum(axis=1, keepdims=True)

array([[6],
       [2],
       [4],
       [5],
       [0]])

In [ ]:
security_breaches.cumsum(axis=0)

array([[ 0,  5,  1],
       [ 0,  7,  1],
       [ 1,  8,  3],
       [ 3, 10,  4],
       [ 3, 10,  4]], dtype=int32)

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
for row in range(array.shape[0]):
    for column in range(array.shape[1]):
        array[row][column] += 3
array

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[0, 1, 0], [1, 0, 1]])
array_a + array_b

array([[1, 3, 3],
       [5, 5, 7]])

In [ ]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[0, 1, 0], [1, 0, 1]])
array_a * array_b

array([[0, 2, 0],
       [4, 0, 6]])

In [ ]:
array = np.arange(10).reshape((2, 5))
array + np.array([0, 1, 2, 3, 4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [ ]:
arr = np.array([1, 2, 3, 2, 4, 1])
np.unique(arr)

array([1, 2, 3, 4])

In [ ]:
np.linspace(0, 1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
x=np.array([1, 2, 3, 5, 6, 7]) #Deleting elements

In [ ]:
np.delete(x, 0) #(array, position)

array([2, 3, 5, 6, 7])

In [ ]:
np.delete(x, (0, 5))

array([2, 3, 5, 6])

In [ ]:
w = np.arange(1, 10).reshape(3, 3)
v = np.delete(w, 0, axis = 0) #From the x axis in w array delete the first row
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
v

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
w = np.arange(1, 10).reshape(3, 3)
v = np.delete(w, [0, 1], axis = 1) #From the x axis in w array delete the first and second column
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
v

array([[3],
       [6],
       [9]])

In [ ]:
import numpy as np

# Create an example ndarray
arr = np.array([1, 2, 3, 4, 5])

# Select the elements to delete
elements_to_delete = [2, 4]

# Create a boolean mask indicating the elements to delete
mask = np.isin(arr, elements_to_delete)

# Delete the selected elements
new_arr = arr[~mask]

print(new_arr)

[1 3 5]


In [ ]:
x = np.array([1, 2, 3, 5, 6, 7]) # Append element to array

In [ ]:
y = np.append(x, 8) # append into x array 8 in the last index #(array, element)
y

array([1, 2, 3, 5, 6, 7, 8])

In [ ]:
y = np.append(x, (8, 9)) # append into x array 8 & 9 in the last index
y

array([1, 2, 3, 5, 6, 7, 8, 9])

In [ ]:
w = np.arange(1, 10).reshape(3, 3)
w1 = np.append(w, [[10, 11, 12]], axis = 0) # Add a row to w array with values 10, 11, 12 at the end #(array, elements, axis)
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
w1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
w = np.arange(1, 10).reshape(3, 3)
w1 = np.append(w, [[10], [11], [12]], axis = 1) # Add a column to w array with values 10, 11, 12 at the end
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
w1

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [ ]:
w = np.arange(1, 10).reshape(3, 3)
v = np.insert(w, 1, [[10, 11, 12]], axis = 0) # Add a row to w array with values 10, 11, 12 at the specific index
w
# =np.vstack((x,y,z,.......))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
v

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
w = np.arange(1, 10).reshape(3, 3)
v = np.insert(w, 1, [10,11, 12], axis = 1) # Add a row to w array with values 10, 11, 12 at the specific index
w  # (array, index, elements, axis)
# =np.hstack((x,y,z,.......))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
v

array([[ 1, 10,  2,  3],
       [ 4, 11,  5,  6],
       [ 7, 12,  8,  9]])

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 2, 8, 9, 10])

In [ ]:
interset = np.intersect1d(x,y)
interset

array([2])

In [ ]:
diff = np.setdiff1d(y,x)
diff

array([ 6,  8,  9, 10])

In [ ]:
union = np.union1d(x,y)
union

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])